name: leak_tracker
version: 9.0.13
description: A framework for memory leak tracking for Dart and Flutter applications.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/leak_tracker

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  async: ^2.5.0
  clock: ^1.1.1
  collection: ^1.15.0
  intl: ^0.18.0
  meta: ^1.8.0
  path: ^1.8.3
  stream_channel: ^2.1.2
  vm_service: '>=11.10.0 <14.0.0'

dev_dependencies:
  flutter_lints: ^3.0.0
  layerlens: ^1.0.0
  test: ^1.16.0
