name: leak_tracker
version: 7.0.4
description: A framework for memory leak tracking for Dart and Flutter applications.
repository: https://github.com/dart-lang/leak_tracker

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  clock: ^1.1.1
  collection: ^1.15.0
  intl: ^0.18.1
  logging: ^1.1.1
  meta: ^1.8.0
  path: ^1.8.3
  vm_service: '>=11.6.0 <13.0.0'
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  layerlens:
  leak_tracker_testing: ^1.0.0
  integration_test:
    sdk: flutter
  test: ^1.16.0
