name: leak_tracker
version: 1.0.0-dev
description: A framework for memory leak tracking for Dart and Flutter applications.
repository: https://github.com/dart-lang/leak_tracker

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  test: ^1.16.0
