name: leak_tracker
version: 2.0.1-dev.1.2
description: A framework for memory leak tracking for Dart and Flutter applications.
repository: https://github.com/dart-lang/leak_tracker

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  clock: ^1.1.1
  collection: ^1.15.0
  matcher: ^0.12.13
  meta: ^1.8.0
  test: ^1.16.0
  vm_service: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter:
    sdk: flutter
  layerlens: ^1.0.9
