name: memory_usage
version: 0.1.0
description: A framework for memory usage tracking and snapshotting.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/memory_usage

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  intl: ^0.18.0
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^3.0.0
  layerlens: ^1.0.0
  test: ^1.16.0
