name: leak_tracker_flutter_testing
version: 1.0.11-wip
description: An internal package to test leak tracking with Flutter.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/leak_tracker_flutter_testing

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  leak_tracker: ^9.0.10
  leak_tracker_testing: ^1.0.5
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
