name: leak_tracker_flutter_testing
version: 3.0.3
description: An internal package to test leak tracking with Flutter.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/leak_tracker_flutter_testing

environment:
  sdk: ^3.2.0
  flutter: '>=3.18.0-18.0.pre.54'

dependencies:
  flutter:
    sdk: flutter
  leak_tracker: '>=10.0.4 <11.0.0'
  leak_tracker_testing: '>=3.0.1 <4.0.0'
  matcher: ^0.12.16
  meta: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.0
  test: ^1.25.0
