name: leak_tracker_flutter_testing
version: 2.0.1
description: An internal package to test leak tracking with Flutter.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/leak_tracker_flutter_testing

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  leak_tracker: '>=10.0.0 <11.0.0'
  leak_tracker_testing: '>=2.0.1 <3.0.0'
  matcher: ^0.12.16
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
