name: leak_tracker_testing
version: 1.0.3
description: Leak tracking code intended for usage in tests.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/leak_tracker_testing

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  leak_tracker: '>=10.0.0 <11.0.0'
  test: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.0
  layerlens:

dependency_overrides:
  leak_tracker:
    path: ../leak_tracker
