name: leak_tracker_testing
version: 3.0.1
description: Leak tracking code intended for usage in tests.
repository: https://github.com/dart-lang/leak_tracker/tree/main/pkgs/leak_tracker_testing

environment:
  sdk: ^3.2.0

# All dependencies here will become Flutter transitive dependencies.
# Follow the process when adding:
# https://github.com/flutter/flutter/blob/2be9b613099250cf8e84e1498a7624d9d2e04023/dev/bots/allowlist.dart#L13
dependencies:
  leak_tracker: '>=9.0.0 <11.0.0'
  matcher: ^0.12.16
  meta: ^1.11.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.0
  layerlens: ^1.0.0
  test: ^1.16.0
