name: leak_tracker_minimal_dart_example
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  leak_tracker: any

dev_dependencies:
  lints: ^4.0.0

dependency_overrides:
  leak_tracker:
    path: ..
